services:
  db:
    image: mysql:8.0.30-debian
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/db:/var/lib/mysql
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app